apiVersion: apps/v1
kind: Deployment
metadata:
  name: sshd-deployment
  labels:
    app: sshd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sshd
  template:
    metadata:
      labels:
        app: sshd
    spec:
      containers:
      - name: sshd
        image: megzo/docker-sshd:latest
        env:
        - name: SSHPORT
          value: "2000"
        - name: SSHPASSWORD
          value: admin123
---
apiVersion: v1
kind: Service
metadata:
  name: sshd
spec:
  selector:
    app: sshd
  ports:
  - protocol: TCP
    port: 22
    targetPort: 2000
  type: NodePort